on:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

name: Debuggable Container
jobs:
  debug:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
    - uses: actions/checkout@v4
    - name: Setup upterm session
      uses: lhotari/action-upterm@d23c2722bdab893785c9fbeae314cbf080645bd7
      with:
        limit-access-to-actor: true
